# Generated by Django 4.1.7 on 2023-04-21 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('site', models.CharField(max_length=500, verbose_name='Сайт')),
                ('file1', models.CharField(max_length=500, verbose_name='Ссылка на файл №1')),
                ('file2', models.CharField(max_length=500, verbose_name='Ссылка на файл №2')),
                ('file3', models.CharField(max_length=500, verbose_name='Ссылка на файл №3')),
                ('file4', models.CharField(max_length=500, verbose_name='Ссылка на файл №4')),
                ('file5', models.CharField(max_length=500, verbose_name='Ссылка на файл №5')),
                ('youtube1', models.CharField(max_length=500, verbose_name='Ссылка на Youtue №1')),
                ('youtube2', models.CharField(max_length=500, verbose_name='Ссылка на Youtue №2')),
                ('youtube3', models.CharField(max_length=500, verbose_name='Ссылка на Youtue №3')),
                ('youtube4', models.CharField(max_length=500, verbose_name='Ссылка на Youtue №4')),
                ('youtube5', models.CharField(max_length=500, verbose_name='YouСсылка на Youtue №5')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Инструкция',
                'verbose_name_plural': 'Инструкции',
                'ordering': ('-created_date',),
            },
        ),
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('image', models.ImageField(blank=True, upload_to='news/', verbose_name='Картинка')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ('-created_date',),
            },
        ),
    ]
