# Generated by Django 4.1.7 on 2023-05-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_instructionmodel_newsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube', models.CharField(max_length=500, verbose_name='Youtube')),
                ('site', models.CharField(max_length=500, verbose_name='Сайт')),
            ],
        ),
        migrations.RemoveField(
            model_name='instructionmodel',
            name='file1',
        ),
        migrations.RemoveField(
            model_name='instructionmodel',
            name='file2',
        ),
        migrations.RemoveField(
            model_name='instructionmodel',
            name='file3',
        ),
        migrations.RemoveField(
            model_name='instructionmodel',
            name='file4',
        ),
        migrations.RemoveField(
            model_name='instructionmodel',
            name='file5',
        ),
        migrations.RemoveField(
            model_name='instructionmodel',
            name='youtube1',
        ),
        migrations.RemoveField(
            model_name='instructionmodel',
            name='youtube2',
        ),
        migrations.RemoveField(
            model_name='instructionmodel',
            name='youtube3',
        ),
        migrations.RemoveField(
            model_name='instructionmodel',
            name='youtube4',
        ),
        migrations.RemoveField(
            model_name='instructionmodel',
            name='youtube5',
        ),
        migrations.AddField(
            model_name='instructionmodel',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='instructionmodel',
            name='visibility',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='visibility',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='program',
            name='type',
            field=models.CharField(default=1, max_length=255, verbose_name='Тип программы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='visibility',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='created_date',
            field=models.DateTimeField(verbose_name='Дата публикации'),
        ),
    ]
