# Generated by Django 4.1.7 on 2024-01-20 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_urlmodel_remove_instructionmodel_file1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urlmodel',
            options={'verbose_name': 'Ссылки', 'verbose_name_plural': 'Ссылки'},
        ),
    ]
