# Generated by Django 4.1.7 on 2024-01-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_program_level_alter_instructionmodel_site'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ('-priority', '-created_date')},
        ),
        migrations.AddField(
            model_name='instructionmodel',
            name='level',
            field=models.CharField(choices=[('A', 'Для любого пользователя'), ('B', 'Для зарегестрированного'), ('C', 'Для админа')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='level',
            field=models.CharField(choices=[('A', 'Для любого пользователя'), ('B', 'Для зарегестрированного'), ('C', 'Для админа')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='program',
            name='priority',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='urlmodel',
            name='site',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Сайт'),
        ),
        migrations.AlterField(
            model_name='urlmodel',
            name='youtube',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Youtube'),
        ),
    ]
